/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.wikiviewerapp.model;

public class Comment {
    private Integer commentId;     // generated by DB
    private int articlePageId;     // FK to Article.PAGEID (NOT NULL)
    private String textOfComment;  // NOT NULL

    public Comment(int articlePageId, String textOfComment) {
        this.articlePageId = articlePageId;
        this.textOfComment = textOfComment;
    }

    public Integer getCommentId() { return commentId; }
    public void setCommentId(Integer commentId) { this.commentId = commentId; }

    public int getArticlePageId() { return articlePageId; }
    public void setArticlePageId(int articlePageId) { this.articlePageId = articlePageId; }

    public String getTextOfComment() { return textOfComment; }
    public void setTextOfComment(String textOfComment) { this.textOfComment = textOfComment; }
    
    
}
