package com.mycompany.wikiviewerapp.gui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author ioann
 */
public class Jgui_0 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Jgui_0.class.getName());

    /**
     * Creates new form Jgui_0
     */
    public Jgui_0() {
        initComponents();

        setTitle("WikiViewer - Menu");
        setSize(900, 450);
        //Δεν επιτρέπει να γίνει το παράθυρο μικρότερο από αυτό το μέγεθος
        setMinimumSize(new Dimension(900, 450));
        //Τοποθετώ το εικονίδιο πάνω αριστερά και στο popup
        Image icon = new ImageIcon(Jgui_0.class.getResource("/wikilogo.png")).getImage();
        setIconImage(icon);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        JPanel mainUI = new JPanel(new BorderLayout(10, 10));

        JLabel title = new JLabel("Choose an option:");
        title.setHorizontalAlignment(SwingConstants.CENTER);
        //Τοποθετώ τον τίτλο στο Jpanel MainUI
        mainUI.add(title, BorderLayout.NORTH);

        JPanel options = new JPanel(new GridLayout(9, 1, 10, 10));

        //Τοποθέτηση κειμένου στα κουμπιά
        jButton1.setText("1. Αναζήτηση άρθρου (Live από το API)");
        jButton2.setText("2. Ενημέρωση πληροφοριών άρθρου (στην τοπική ΒΔ)");
        jButton3.setText(" 3. Προσθήκη πληροφοριών για άρθρο (π.χ. σχόλια, βαθμολογία)");
        jButton4.setText(" 4. Προβολή αποθηκευμένων άρθρων ανά κατηγορία ");
        jButton5.setText(" 5. Αναζήτηση άρθρου βάσει keyword (σε τίτλο ή κείμενο) ");
        jButton6.setText(" 6. Προβολή στατιστικών ");
        jButton7.setText(" 7. Προσθήκη νέου άρθρου σε κατηγορία (Χειροκίνητη εισαγωγή)");
        jButton8.setText(" 8. Τροποποίηση άρθρων σε κατηγορία ");
        jButton9.setText("9. Προσθήκη κατηγορίας");

        //Τοποθέτηση στο Jpanel options
        options.add(jButton1);
        options.add(jButton2);
        options.add(jButton3);
        options.add(jButton4);
        options.add(jButton5);
        options.add(jButton6);
        options.add(jButton7);
        options.add(jButton8);
        options.add(jButton9);
        //Τοποθετώ το Jpanel options και αυτό στο Jpanel MainUI
        mainUI.add(options, BorderLayout.CENTER);
        mainUI.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setContentPane(mainUI);

        //Το κάνω Refresh
        revalidate();
        repaint();

        //Φτιάχνω τα events για τα click του mouse
        jButton1.addActionListener(e -> {
            setVisible(false);
            new Jgui1_1(this).setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.setPreferredSize(new java.awt.Dimension(420, 23));

        jButton2.setText("jButton2");
        jButton2.setPreferredSize(new java.awt.Dimension(420, 23));

        jButton3.setText("jButton3");
        jButton3.setPreferredSize(new java.awt.Dimension(420, 23));

        jButton4.setText("jButton4");
        jButton4.setPreferredSize(new java.awt.Dimension(420, 23));

        jButton5.setText("jButton5");
        jButton5.setPreferredSize(new java.awt.Dimension(420, 23));

        jButton6.setText("jButton6");
        jButton6.setPreferredSize(new java.awt.Dimension(420, 23));

        jButton7.setText("jButton7");
        jButton7.setPreferredSize(new java.awt.Dimension(420, 23));

        jButton8.setText("jButton8");
        jButton8.setPreferredSize(new java.awt.Dimension(420, 23));

        jButton9.setText("jButton9");
        jButton9.setPreferredSize(new java.awt.Dimension(420, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
